### PR TITLE
Updated MockBukkit, added docs and lots of improvements.

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
* I recently added all tags from Minecraft into MockBukkit itself, therefore there is no longer any need to mock these, so I removed that section and updated the MockBukkit dependency
* I refactored/renamed some methods and parameters
* I added lots of documentation

You should also definitely add a `LICENSE` and `README` here.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
:eyes:

**Comment by WalshyDev** [comment]
Oh hi, shit. I will check very shortly. Let me finish eating

**Comment by TheBusyBiscuit** [comment]
No need to hurry. This is far from important :LUL:
I just thought 3 months was a good mark when to bump XD

**Review by WalshyDev — APPROVED** [review]
LGTM

**Pull request merged**
